### ISSUE TITLE
image_gt_data_layer.cpp:444 Could not open or find file

### ISSUE THREAD

**Issue by Yanhui-He** [gdlg/panoramic-object-detection#1]
E1116 12:17:43.236814 12063 image_gt_data_layer.cpp:444] Could not open or find file /home/amax/hyh/panoramic/panoramic-object-detection-master/data/kitti/object/training/image_2_miami/005350.png

my dir e.g.:
/home/amax/hyh/panoramic/panoramic-object-detection-master/data/kitti/object/training/image_2_miami/miami-kitti/train_4/images and index.html

**Comment by gdlg** [comment]
Hi Yanhui,

I am not entirely sure what you mean and what is the index.html?

The path for each image is defined in the window_files folders generated by `create_labels.sh`. If you would like to use a different path, then you must either adapt the generation code or change the path directly in the window_files. Depending on the example that you are trying to run, it might be in `mscnn-panomono/data/miami/window_files/vehicle_trainval.txt`.

**Comment by Yanhui-He** [comment]
@gdlg 

Hi gdlg，

Thank you very much for your reply.

I have solved the problem. This wonderful paper is currently being studied.

**Comment by gdlg** [comment]
Thank you very much. I am glad that you solved the problem.
