### ISSUE TITLE
can't use with image without label

### ISSUE THREAD

**Issue by TanuTSure** [gdlg/panoramic-object-detection#4]
Hi gdlg,
     When I try feeding my image into the model, this error pops up `RuntimeError: Could not open file examples/inference/deploy_rectilinear.prototxt` Is this because of my image does't have a label or it is because something else ?

**Comment by gdlg** [comment]
Hi @TanuTSure ,
No, as written in the error message, this means that it fails to find the file `examples/inference/deploy_rectilinear.prototxt`. I have double-checked and this file is in this repo so I am not really sure why it can’t find it. Perhaps you are running the script from the wrong directory or deleted the file by mistake. I would suggest that you check whether the file is present in your clone of the repo.

**Comment by TanuTSure** [comment]
Dear @gdlg ,
Thank you for a fast response. I am trying to feed my own dataset into a trained model and it does not have any label. Is the label neccesary in this prediction step? The video posted on YouTube does not seem to require any label.

**Comment by TanuTSure** [comment]
Got it. Thank you so much.
